add carousel
TheMainOne/team-project pull request #132
Opened 2021-12-19 16:28 UTC by Natatashkin

create Carousel and insert my calling of functions to another files: change-theme.js, film-in-modal-window.js, for-queue-btn.js, for-watched-local-storage.js. Change markup in gallery.html: insert Carousel layout. Modifyed listener of My-library "click".

2021-12-19 17:21 UTC, TheMainOne commented
Если нажать в модалке на добавить в кью или вотчед и затем сразу же удалить оттуда фильм появляется снег поверх всего на главной странице 
http://joxi.ru/EA4Y1ZzuvVB8Kr

2021-12-19 17:22 UTC, KostiantynO requested changes

2021-12-19 17:22 UTC, KostiantynO commented on src/js/carousel.js
> +    setBgSnow();
Давай перешем эту логику, пожалуйста.
Потому что из-за нее снежинки рендерятся 2 раза -> удаляются -> и тут же создаются заново.

2021-12-19 17:23 UTC, TheMainOne commented
В нашей библиотеке если клацать между кью и вотчед начинает глючить снег

2021-12-19 17:25 UTC, KostiantynO commented on src/js/carousel.js
> +    setBgSnow();
Предлагаю привести к стандартным именам, чтобы не запутатся
rengerCarousel -> renderCarousel
onLinraryBtnClick -> onLibraryBtnClick
localstorageKey -> localStorageKey
decktopMedia -> desktopMedia

2021-12-19 23:03 UTC, Natatashkin commented on src/js/carousel.js
> +    setBgSnow();
поменяла :)

2021-12-19 23:33 UTC, KostiantynO approved these changes, later dismissed
Проверил в VSCode - все работает!
Есть один мелкий баг - надо починить - переставить 1 строчку кода в другое место ))))

Чтобы было так:
  if (inLibrary) {
    renderCarousel(QUEUE, carouselListQueue, carouselQueue, gifQueue);
    carousel.classList.remove('is-hidden');
  }

2021-12-19 23:33 UTC, KostiantynO commented on src/js/for-queue-btn.js
> +    carousel.classList.remove('is-hidden');
Вызываем функционал, связанный с Library - только в условии проверки, что мы на странице 'library'
carousel.classList.remove('is-hidden');  - 36ю строку переместим в условие после 42 строки.

2021-12-19 23:33 UTC, KostiantynO commented on src/js/for-queue-btn.js
> +  }
Предлагаю так:
  if (inLibrary) {
    renderCarousel(QUEUE, carouselListQueue, carouselQueue, gifQueue);
    carousel.classList.remove('is-hidden');
  }

2021-12-19 23:33 UTC, KostiantynO commented on src/js/film-in-modal-window.js
> +carousel.addEventListener('click', async event => {
Можно вынести колбек в eventListener в отдельную функцию, так как одинаковый функционал. Но это потом :))) То есть никогда )))

2021-12-20 08:31 UTC, TheMainOne commented
Пока не принимаем, есть что исправить
http://joxi.ru/V2V7pgLT8j5zjA

2021-12-20 09:00 UTC, Natatashkin commented on src/js/film-in-modal-window.js
> +carousel.addEventListener('click', async event => {
я пробовала, через колбек функцию, перестало работать вообще. Код идентичен, обернула в функцию, сделала асинхронной, но так не срабатывало. потому оставила так как есть. Баг с каруселью поправила ))))

2021-12-20 09:00 UTC, Natatashkin commented on src/js/for-queue-btn.js
> +  }
+

2021-12-20 09:00 UTC, Natatashkin commented on src/js/for-queue-btn.js
> +    carousel.classList.remove('is-hidden');
+

2021-12-20 09:16 UTC, TheMainOne approved these changes

2021-12-20 09:16 UTC, merged