Feature/variables
TheMainOne/team-project pull request #15
Opened 2021-12-02 22:02 UTC by Yuliia-Lysiuk

добавила паршали, scss компоненти, підключила шрифти, створила змінні, створила контейнер

2021-12-02 22:35 UTC, anastasia1756 requested changes

2021-12-02 22:35 UTC, anastasia1756 commented on src/sass/base/_container.scss
> +.conteiner {
Опечатка у тебя, contAiner надо, подправь пожалуйста

2021-12-02 22:40 UTC, Yuliia-Lysiuk commented on src/sass/base/_container.scss
> +.conteiner {
вже виправила)

2021-12-02 23:03 UTC, anastasia1756 commented
Надо еще резолвнуть конфликт у себя локально, без этого кажется не могу принять твой пул реквест

2021-12-02 23:09 UTC, dimahalaiskiy approved these changes, later dismissed

2021-12-02 23:12 UTC, anastasia1756 submitted a review, later dismissed

2021-12-03 08:52 UTC, TheMainOne requested changes

2021-12-03 08:52 UTC, TheMainOne commented on src/sass/utils/_variables.scss
> +$main-font: 'Roboto', sans-serif;
Юль, у тебя дважды продублированы одни и те же стили, исправь пожалуйста

2021-12-03 08:52 UTC, TheMainOne commented on src/sass/base/_container.scss
> +  padding: 20px;
Юль, оставь пожалуйста только горизонтальные паддинги

2021-12-03 08:52 UTC, TheMainOne commented on src/sass/base/_container.scss
> +    padding: 60px 70px;
только горизонтальные

2021-12-03 08:52 UTC, TheMainOne commented on src/sass/base/_container.scss
> +    padding: 60px 75px;
только горизонтальные

2021-12-03 10:15 UTC, merged