add htms + css  film in modal (mobile)
TheMainOne/team-project pull request #21
Opened 2021-12-03 12:55 UTC by AlexKarb

2021-12-03 13:10 UTC, anastasia1756 commented on src/partials/modal-window.html
> +<button type="submit" class="movie__btn btn btn--accent"> add to <br> Watched </button>
Думаю что br тут не надо, потому что на планшете и десктопе нету переноса

2021-12-03 13:12 UTC, anastasia1756 commented on src/sass/layout/_btn.scss
> +    background-color: #ff6b01;
чего не используешь variables? не уверена конечно, но на вертске нам ментор говорил убирать все повторения и все заносить в переменные и их переиспользовать

2021-12-03 15:21 UTC, AlexKarb commented on src/sass/layout/_btn.scss
> +    background-color: #ff6b01;
потому что их еще не написали

2021-12-03 15:22 UTC, AlexKarb commented on src/sass/layout/_btn.scss
> +    background-color: #ff6b01;
как появятся - поменяю

2021-12-03 18:42 UTC, anastasia1756 commented on src/sass/layout/_btn.scss
> +    background-color: #ff6b01;
Они ещё вчера добавились, попробуй найти

2021-12-03 18:44 UTC, AlexKarb commented on src/sass/layout/_btn.scss
> +    background-color: #ff6b01;
уже все добавлено

2021-12-03 23:01 UTC, KostiantynO submitted a review, later dismissed
Rectangle 18.jpg - делаем название с маленьких, без пробелов, пожалуйста :)
Класс .test еще нужен ? :)
flex-direction: row - это по умолчанию во flex'ах.

2021-12-03 23:01 UTC, KostiantynO commented on src/partials/modal-window.html
> +</div>
Предлагаю автоформатированием выровнять "div"ы на 54-56 строках ))

2021-12-03 23:01 UTC, KostiantynO commented on src/sass/layout/_modal-window.scss
> +    flex-direction: row;
flex-direction: row - это по умолчанию

2021-12-03 23:01 UTC, KostiantynO commented on src/sass/layout/_modal-window.scss
> +.test {
Класс тест еще нужен ? :)

2021-12-03 23:06 UTC, KostiantynO approved these changes, later dismissed

2021-12-03 23:07 UTC, KostiantynO commented
Комменты выше.

2021-12-04 09:59 UTC, TheMainOne requested changes

2021-12-04 09:59 UTC, TheMainOne commented on src/sass/main.css
> -.gallery__list {
Почему убираешь стили с галереи?

2021-12-04 09:59 UTC, TheMainOne commented on src/sass/main.css
> -    padding-right: 75px;
Паддинги у нас уже настроены, менять не надо

2021-12-04 10:18 UTC, TheMainOne commented on src/sass/layout/_modal-window.scss
> +.test {
не нужен)

2021-12-04 11:46 UTC, merged